---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__create_and_modify_resource_groups.html 
keywords:  
summary: VMware vSphere REST API용 SnapCenter 플러그인을 사용하여 리소스 그룹 작업을 생성하고 수정하려면 규정된 REST API 호출 순서를 따라야 합니다. 
---
= 리소스 그룹을 생성 및 수정하는 REST API 워크플로우
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vSphere REST API용 SnapCenter 플러그인을 사용하여 리소스 그룹 작업을 생성하고 수정하려면 규정된 REST API 호출 순서를 따라야 합니다.

각 REST API에 대해 REST API 앞에 를 `\https://<server>:<port>` 추가하여 전체 엔드포인트를 구성합니다.

리소스 그룹을 만들려면 다음 워크플로를 따릅니다.

|===
| 단계 | REST API | 설명 


| 1 | `/4.1/policies` | `Get Policies` VMware vSphere 클라이언트 정책 목록을 가져옵니다. 리소스 그룹 및 정책 * 빈도 * 를 만들 때 사용할 * 정책 ID * 를 확인합니다. 나열된 정책이 없는 경우 REST API를 사용하여 `Create Policy` 새 정책을 생성합니다. 


| 2 | `/4.1/resource-groups` | `Create a Resource Group` 지정된 정책을 사용하여 리소스 그룹을 생성합니다. 1단계에서 * policyId * 를 전달하고 다른 모든 필수 속성 외에 * frequency * 정책 세부 정보를 입력합니다. 
|===
리소스 그룹을 수정하려면 다음 워크플로우를 따르십시오.

|===
| 단계 | REST API | 설명 


| 1 | `/4.1/resource-groups` | `Get List of Resource Groups` VMware vSphere Client 리소스 그룹의 목록을 가져옵니다. 수정할 * resourceGroupId * 를 확인합니다. 


| 2 | `/4.1/policies` | 할당된 정책을 수정하려면 `Get Policies` VMware vSphere Client 정책 목록을 가져옵니다. 리소스 그룹 및 정책 * 빈도 * 를 수정할 때 사용할 * 정책 ID * 를 확인합니다. 


| 3 | `/4.1/resource-groups/
{resouceGroupId}` | `Update a Resource Group` 지정된 리소스 그룹을 수정합니다. 1단계에서 * resourceGroupId * 를 전달합니다. 필요한 경우 2단계에서 * policyId * 를 전달하고 다른 모든 필수 속성 외에 * frequency * 세부 정보를 입력합니다. 
|===