---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_vms.html 
keywords:  
summary: VMware vSphere REST API용 SnapCenter 플러그인을 사용하여 VM 백업에 대한 복구 작업을 수행하려면 규정된 REST API 호출 순서를 따라야 합니다. 
---
= VM 복원을 위한 REST API 워크플로우
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vSphere REST API용 SnapCenter 플러그인을 사용하여 VM 백업에 대한 복구 작업을 수행하려면 규정된 REST API 호출 순서를 따라야 합니다.

각 REST API에 대해 REST API 앞에 를 `\https://<server>:<port>` 추가하여 전체 엔드포인트를 구성합니다.

|===
| 단계 | REST API | 설명 


| 1 | 로 이동합니다 `\http://<vCenter-IP>/mob` | VMware Managed Objects URL에서 VM을 찾습니다. 복원하려는 VM의 * moref * 에 유의하십시오. 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups` 지정된 VM에 대한 백업 목록을 가져옵니다. 1단계에서 * moref * 를 전달합니다. 복원하려는 백업의 * backupId * 를 기록해 둡니다. 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations` 지정된 백업의 스냅샷 위치를 가져옵니다. 2단계에서 * backupId * 를 전달합니다. snapshotLocationsList* 정보를 확인합니다. 


| 4 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts` 백업이 저장된 호스트에 대한 정보를 가져옵니다. 사용 가능한 EsableEsHostsList* 정보를 확인합니다. 


| 5 | `/4.1/vm/{moref}/backups/
{backupId}/restore`  a| 
`Restore a VM from a backup` 지정된 백업을 복원합니다. RestoreLocations * 속성의 3단계와 4단계의 정보를 전달합니다.


NOTE: VM 백업이 부분 백업인 경우 `restartVM` 매개 변수를 "false"로 설정합니다.


NOTE: 템플릿인 VM은 복원할 수 없습니다.

|===